/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventana;
import Control.ControlPersonaje;

/**
 *
 * @author Francisco Puas
 */
public class Personaje extends javax.swing.JFrame   {

    int s;
    int i;
    int d;
    int v;
    int w;
    int lvl=1;
    int Watk=0;
    int Edef;
    int Emdef;
    int hit;
    
   
    //instancia clase Equipo
    Equipo equipo= new Equipo();
    //instancia clase mostrarDatos
    MostrarDatos datos= new MostrarDatos(this,false);
    //instancia Clase ControlPersonaje
    ControlPersonaje control= new ControlPersonaje();
    public Personaje() {
        initComponents();
    }
    
    //controlar ventana de equipo visible y llamar metodo para cambiar color de labels de ventana equipo
    public void MostrarEquipo()
    {
        
        equipo.setVisible(true);
        equipo.cambiarColorFondo();
    }
   
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        SpLabel = new javax.swing.JLabel();
        lblStats = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton11 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jProgressBar2 = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNombre.setText("Nombre");
        jPanel1.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 23, -1, -1));
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 46, 92, -1));

        jLabel2.setText("nivel");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 75, -1, -1));

        jLabel3.setText("1");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 75, -1, -1));

        jLabel4.setText("HP");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 23, -1, -1));

        jLabel5.setText("1");
        jLabel5.setToolTipText("");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(382, 23, -1, -1));

        jLabel6.setText("SP");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 52, -1, -1));

        SpLabel.setText("1");
        SpLabel.setToolTipText("");
        jPanel1.add(SpLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(382, 52, -1, -1));

        lblStats.setText("STATS");
        jPanel1.add(lblStats, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 117, -1, -1));

        jLabel9.setText("STR");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 159, -1, -1));

        jLabel10.setText("INT");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 201, -1, -1));

        jLabel11.setText("DEX");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 248, -1, -1));

        jLabel12.setText("VIT");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 300, -1, -1));

        jLabel13.setText("WIS");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 348, -1, -1));

        jButton1.setText("+");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 150, -1, -1));

        jButton2.setText("+");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 197, -1, -1));

        jButton3.setText("+");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 244, -1, -1));

        jButton4.setText("+");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 296, -1, -1));

        jButton5.setText("+");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 344, -1, -1));

        jButton6.setText("-");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 150, -1, -1));

        jButton7.setText("-");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 197, -1, -1));

        jButton8.setText("-");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 244, -1, -1));

        jButton9.setText("-");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 296, -1, -1));

        jButton10.setText("-");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 344, -1, -1));

        jLabel14.setText("0");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 150, -1, -1));

        jLabel15.setText("0");
        jLabel15.setToolTipText("");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 197, -1, -1));

        jLabel16.setText("0");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 244, -1, -1));

        jLabel17.setText("0");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 296, -1, -1));

        jLabel18.setText("0");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 344, -1, -1));

        jLabel19.setText("MATK");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 182, -1, -1));
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(499, 154, -1, -1));

        jLabel21.setText("ATK");
        jLabel21.setToolTipText("");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 153, -1, -1));
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(499, 182, -1, -1));

        jLabel23.setText("DEF");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 216, -1, -1));
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(499, 216, -1, -1));

        jLabel25.setText("MDEF");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(401, 250, -1, -1));
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(499, 250, -1, -1));

        jLabel27.setText("HIT");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(401, 287, -1, -1));
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(499, 287, -1, -1));

        jLabel29.setText("Clase");
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 23, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "class select", "Warrior", "Mage", "Archer", "Priest" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 46, 120, -1));

        jButton11.setText("Guardar");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 400, -1, -1));

        jLabel7.setText("puntos disponibles");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, -1, -1));

        jLabel30.setText("10");
        jPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 400, -1, -1));
        jPanel1.add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, -1, -1));
        int s= Integer.parseInt(jLabel5.getText());
        jProgressBar1.setMaximum(s);
        jProgressBar1.setMinimum(0);
        jProgressBar1.setStringPainted(true);
        jPanel1.add(jProgressBar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, -1, -1));
        int sp= Integer.parseInt(SpLabel.getText());
        jProgressBar2.setMaximum(sp);
        jProgressBar2.setMinimum(0);
        jProgressBar2.setStringPainted(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 716, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 487, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    //control del comboBox
    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        String stats="10";
        if(jComboBox1.getSelectedItem().equals("Warrior"))
        {
            s=9;
            i=1;
            d=4;
            v=8;
            w=3;
            jLabel14.setText(Integer.toString(s));
            jLabel15.setText(Integer.toString(i));
            jLabel16.setText(Integer.toString(d));
            jLabel17.setText(Integer.toString(v));
            jLabel18.setText(Integer.toString(w));
            jLabel30.setText(stats);
        }
         if(jComboBox1.getSelectedItem().equals("Mage"))
        {
            s=1;
            i=9;
            d=5;
            v=3;
            w=6;
            jLabel14.setText(Integer.toString(s));
            jLabel15.setText(Integer.toString(i));
            jLabel16.setText(Integer.toString(d));
            jLabel17.setText(Integer.toString(v));
            jLabel18.setText(Integer.toString(w));
            jLabel30.setText(stats);
        }
          if(jComboBox1.getSelectedItem().equals("Archer"))
        {
            s=6;
            i=3;
            d=9;
            v=4;
            w=3;
            jLabel14.setText(Integer.toString(s));
            jLabel15.setText(Integer.toString(i));
            jLabel16.setText(Integer.toString(d));
            jLabel17.setText(Integer.toString(v));
            jLabel18.setText(Integer.toString(w));
            jLabel30.setText(stats);
        }
           if(jComboBox1.getSelectedItem().equals("Priest"))
        {
            s=4;
            i=7;
            d=4;
            v=6;
            w=7;
            jLabel14.setText(Integer.toString(s));
            jLabel15.setText(Integer.toString(i));
            jLabel16.setText(Integer.toString(d));
            jLabel17.setText(Integer.toString(v));
            jLabel18.setText(Integer.toString(w));
            jLabel30.setText(stats);
        }
           if(jComboBox1.getSelectedItem().equals("class select"))
        {
            
            jLabel14.setText(Integer.toString(0));
            jLabel15.setText(Integer.toString(0));
            jLabel16.setText(Integer.toString(0));
            jLabel17.setText(Integer.toString(0));
            jLabel18.setText(Integer.toString(0));
            jLabel30.setText(stats);
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed
        //control botones de sumar-restar stats
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int Istats= control.stats(jLabel30.getText());
        if(Istats>=1 && jComboBox1.getSelectedIndex()!=0)
        {
        Istats=Istats-1;
        jLabel30.setText(String.valueOf(Istats));
        String cn= control.botonSuma(jLabel14.getText());
        jLabel14.setText(cn);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
            
            String cn=control.botonResta(jLabel14.getText());
        int Istats= control.stats(jLabel30.getText());
        if((Integer.parseInt(cn))>=0 && Istats>=0  && jComboBox1.getSelectedIndex()!=0)
        {    
        jLabel14.setText(cn);
        Istats=Istats+1;
        jLabel30.setText(String.valueOf(Istats));
        
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
            int Istats= control.stats(jLabel30.getText());
        if(Istats>=1 && jComboBox1.getSelectedIndex()!=0)
        {
        Istats=Istats-1;
        jLabel30.setText(String.valueOf(Istats));
        String cn= control.botonSuma(jLabel15.getText());
        jLabel15.setText(cn);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
            String cn=control.botonResta(jLabel15.getText());
        int Istats= control.stats(jLabel30.getText());
        if((Integer.parseInt(cn))>=0 && Istats>=0 && jComboBox1.getSelectedIndex()!=0)
        {    
        jLabel15.setText(cn);
        Istats=Istats+1;
        jLabel30.setText(String.valueOf(Istats));
        
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       
        int Istats= control.stats(jLabel30.getText());
        if(Istats>=1 && jComboBox1.getSelectedIndex()!=0)
        {
        Istats=Istats-1;
        jLabel30.setText(String.valueOf(Istats));
        String cn= control.botonSuma(jLabel16.getText());
        jLabel16.setText(cn);
        }
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        String cn=control.botonResta(jLabel16.getText());
        int Istats= control.stats(jLabel30.getText());
        if((Integer.parseInt(cn))>=0 && Istats>=0 && jComboBox1.getSelectedIndex()!=0)
        {    
        jLabel16.setText(cn);
        Istats=Istats+1;
        jLabel30.setText(String.valueOf(Istats));
        
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int Istats= control.stats(jLabel30.getText());
        if(Istats>=1 && jComboBox1.getSelectedIndex()!=0)
        {
        Istats=Istats-1;
        jLabel30.setText(String.valueOf(Istats));
        String cn= control.botonSuma(jLabel17.getText());
        jLabel17.setText(cn);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
       String cn=control.botonResta(jLabel17.getText());
        int Istats= control.stats(jLabel30.getText());
        if((Integer.parseInt(cn))>=0 && Istats>=0 && jComboBox1.getSelectedIndex()!=0)
        {    
        jLabel17.setText(cn);
        Istats=Istats+1;
        jLabel30.setText(String.valueOf(Istats));
        
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        int Istats= control.stats(jLabel30.getText());
        if(Istats>=1 && jComboBox1.getSelectedIndex()!=0)
        {
        Istats=Istats-1;
        jLabel30.setText(String.valueOf(Istats));
        String cn= control.botonSuma(jLabel18.getText());
        jLabel18.setText(cn);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        String cn=control.botonResta(jLabel18.getText());
        int Istats= control.stats(jLabel30.getText());
        if((Integer.parseInt(cn))>=0 && Istats>=0 && jComboBox1.getSelectedIndex()!=0)
        {    
        jLabel18.setText(cn);
        Istats=Istats+1;
        jLabel30.setText(String.valueOf(Istats));
        
        }
    }//GEN-LAST:event_jButton10ActionPerformed
        //control boton para levantar ventana de mostrar
    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        
        
        MostrarDatos.jLabel2.setText(txtNombre.getText());
        MostrarDatos.jLabel9.setText(jLabel14.getText());
        MostrarDatos.jLabel10.setText(jLabel15.getText());
        MostrarDatos.jLabel11.setText(jLabel16.getText());
        MostrarDatos.jLabel12.setText(jLabel17.getText());
        MostrarDatos.jLabel13.setText(jLabel18.getText());
        MostrarDatos.jLabel15.setText(jComboBox1.getSelectedItem().toString());
        MostrarDatos.jLabel17.setText(jLabel3.getText());
        MostrarDatos.jLabel25.setText(jLabel5.getText());
        MostrarDatos.jLabel26.setText(SpLabel.getText());
        MostrarDatos.jLabel27.setText(jLabel20.getText());
        MostrarDatos.jLabel28.setText(jLabel22.getText());
        MostrarDatos.jLabel29.setText(jLabel24.getText());
        MostrarDatos.jLabel30.setText(jLabel26.getText());
        MostrarDatos.jLabel31.setText(jLabel28.getText());
        //llamar metodo para esconder ventana de creacion y equipo desde la clase control
        control.esconder(this,datos,equipo);
    }//GEN-LAST:event_jButton11ActionPerformed
    
    
    //ciclo para claculos de stats en personaje
    public void calculoHp()
    {
        int hp=0;
        int sp;
        int atk;
        int Matk;
        int def;
        int Mdef;
        int hit;
        
        
        do
        {
           
            //calculo hp
        String txt= jLabel17.getText();
        int vit= Integer.parseInt(txt);
        hp= (vit*2)+(2*lvl);
        jLabel5.setText(Integer.toString(hp));
        jProgressBar1.setValue(hp);
        //calculo sp
        String txtSp= jLabel18.getText();
        int wis= Integer.parseInt(txtSp);
        sp= (wis*2)+(1*lvl);
        SpLabel.setText(Integer.toString(sp));
        jProgressBar2.setValue(sp);
        // calculo ATK
        String Satk=jLabel14.getText();
        int Iatk= Integer.parseInt(Satk);
        String Datk= jLabel16.getText();
        int Deatk= Integer.parseInt(Datk);
        atk=(Iatk+1)+(Deatk/2)+Watk;
        jLabel20.setText(Integer.toString(atk));
        // calculo MATK
        String Smatk=jLabel15.getText();
        int Imatk= Integer.parseInt(Smatk);
        Matk=(Imatk+1)+Watk;
        jLabel22.setText(Integer.toString(Matk));
        // calculo defenza
        String Sdef=jLabel17.getText();
        int Idef= Integer.parseInt(Sdef);
        def=Idef+Edef;
        jLabel24.setText(Integer.toString(def));
        //calculo mdef
        String Smdef= jLabel18.getText();
        int Imdef= Integer.parseInt(Smdef);
        Mdef=Imdef+Emdef;
        jLabel26.setText(Integer.toString(Mdef));
        //calculo hit
        String Shit= jLabel16.getText();
        int Ihit= Integer.parseInt(Shit);
        hit=Ihit+(lvl*1);
        jLabel28.setText(Integer.toString(hit));
           
        }while (hp>1);
        
    }
    
    
   
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Personaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Personaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Personaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Personaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Personaje().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel SpLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    public static javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JProgressBar jProgressBar2;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblStats;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
